"""empty message

Revision ID: d75e8f1bc699
Revises: 
Create Date: 2019-07-04 15:35:55.751717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd75e8f1bc699'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('collections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=600), nullable=False),
    sa.Column('tagline', sa.String(length=200), nullable=True),
    sa.Column('cat', sa.Integer(), nullable=False),
    sa.Column('organiser', sa.String(length=20), nullable=False),
    sa.Column('collection', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cat'], ['events.id'], ),
    sa.ForeignKeyConstraint(['collection'], ['collections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eventsto_tags',
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.Column('tagid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eid'], ['events.id'], ),
    sa.ForeignKeyConstraint(['tagid'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('eid', 'tagid')
    )
    op.create_table('tagsto_events',
    sa.Column('tagid', sa.Integer(), nullable=False),
    sa.Column('eid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['eid'], ['events.id'], ),
    sa.ForeignKeyConstraint(['tagid'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('tagid', 'eid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tagsto_events')
    op.drop_table('eventsto_tags')
    op.drop_table('events')
    op.drop_table('tags')
    op.drop_table('collections')
    op.drop_table('cats')
    # ### end Alembic commands ###
